# Generated by Django 4.2.3 on 2023-07-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("todo_id", models.IntegerField()),
                ("content", models.CharField(max_length=200)),
                ("is_done", models.BooleanField()),
            ],
        ),
    ]
