# Generated by Django 4.2.3 on 2023-07-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="id",
        ),
        migrations.AlterField(
            model_name="todo",
            name="todo_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
