# Generated by Django 4.2.3 on 2023-07-09 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_remove_todo_id_alter_todo_todo_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="todo_id",
            new_name="id",
        ),
    ]
